services = [
    "com.inmotionchat.identity.IdentityPlatformService",
    "com.inmotionchat.notifications.NotificationsService",
    "com.inmotionchat.inboxes.InboxesService",
    "com.inmotionchat.journeys.JourneysService",
    "com.inmotionchat.audit.AuditRecordService"
]
