[properties]
    activeNotifiers = []

    [properties.email]
        host = "smtp.gmail.com"
        port = 587
        username = "inmotionchat@gmail.com"
        password = "<USE A GMAIL APP PASSWORD>"