version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=${PG_PASS}'
      - 'POSTGRES_USER=${PG_USER}'
      - 'POSTGRES_DB=${PG_DB}'
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/create-db.sql

  redis:
    container_name: redis
    image: redis:7.0.11
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: 'redis-server --loglevel warning --requirepass ${REDIS_PASS} --save 20 1'

  firebase:
    container_name: firebase
    image: mansehajsingh/inmotion-firebase-emulators:latest
    restart: always
    build:
      dockerfile: './firebase/Dockerfile'
    ports:
      - '9099:9099'
      - '4000:4000'
    volumes:
      - fb_data:/var/firebase/data
      - './firebase/firebase.json:/var/firebase/firebase.json'

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  fb_data:
    driver: local