version: "3.8"

services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=${PG_PASS}'
      - 'POSTGRES_USER=${PG_USER}'
      - 'POSTGRES_DB=${PG_DB}'
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/create-db.sql
volumes:
  pg_data:
    driver: local